### ISSUE TITLE
Error launching task with different name then container

### ISSUE THREAD

**Issue by egreer** [zamarawka/aws-run-fargate-task#1]
I'm testing running my github action with nektos/act locally and my task definition name doesn't match my container name so when I try to deploy it says `Override for container named XXXXXXXX is not a container in the TaskDefinition.`. 

However I'm not overriding `command` or `environment` variable input so I would expect this check to not set any overrides: https://github.com/zamarawka/aws-run-fargate-task/blob/858cf882b4947c18be8a165b9cf52a7105bc30b0/src/runTask.ts#L96

When I do try to override the command and environment (and match container name) I just get: `Error: task "XXXXXXXX " couldn't created! Check out params!` Any way to expose the actual ECS exception to get better diagnostics?

Abriviated and redacted Action setup:

```
   - name: Run Migrations
      uses: zamarawka/aws-run-fargate-task@master
      with:
        task_name: XXXXXXXX 
        cluster: XXXXX-cluster
        count: 1
        sg_filters: |
          Name=tag:Name,Values=YYYYYYYYYY
        subnet_filters: |
          Name=tag:tier,Values=private
          Name=tag:application,Values=ZZZZZZZZ
        wait: true
        timeout: 600
```

Abbriviated and Redacted task definition:

```
{
  "executionRoleArn": "EXECUTION_ARN",
  "taskRoleArn": "TASK_ARN",
  "containerDefinitions": [
    {
      "name": "ZZZZZZZZZZZZZ",
      "image": "",
      "essential": true,
      "mountPoints": [],
      "command": [ "/bin/bash", "/start.sh" ],
      "environment": [ ],
      "secrets": [ ]
    }
  ],
  "volumes": [],
  "memory": "1024",
  "cpu": "256",
  "networkMode": "awsvpc",
  "placementConstraints": [],
  "family": "TASK_FAMILY",
  "requiresCompatibilities": [
    "FARGATE"
  ]
}
```

Full Act Stack Trace:

```
| InvalidParameterException: Override for container named XXXXXXXX is not a container in the TaskDefinition.
|     at Request.extractError (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:8816:27)
|     at Request.callListeners (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:11138:20)
|     at Request.emit (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:11110:10)
|     at Request.emit (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:10483:14)
|     at Request.transition (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:9819:10)
|     at AcceptorStateMachine.runTo (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:13270:12)
|     at /run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:13282:10
|     at Request.<anonymous> (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:9835:9)
|     at Request.<anonymous> (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:10485:12)
|     at Request.callListeners (/run/act/actions/zamarawka-aws-run-fargate-task@master/dist/index.js:11148:18) {
|   code: 'InvalidParameterException',
|   time: 2021-11-19T20:58:16.279Z,
|   requestId: 'ee5d8c43-e093-490d-a17d-81d80e844d23',
|   statusCode: 400,
|   retryable: false,
|   retryDelay: 73.63292599160896
| }
```

Any insight would be great, I really appriciate that this action allows search for subnets and security groups!
