### ISSUE TITLE
A sequence was not expected

### ISSUE THREAD

**Issue by amaia00** [zamarawka/aws-run-fargate-task#5]
Hi I was trying to use the action as follows:

```
      - name: Run my ECS task
        uses: zamarawka/aws-run-fargate-task@v1
        with:
          task_name: task-definition-name
          cluster: cluster-name
          wait: true
          public_ip: false
          subnet_ids: [subnet-1, subnet-2, subnet-3]
          sg_names: [ sg-name ] 
```
But I'm having the following error:

```
Invalid workflow file: .github/workflows/aws.yml#L126
The workflow is not valid. .github/workflows/aws.yml (Line: 126, Col: 23): A sequence was not expected .github/workflows/aws.yml (Line: 127, Col: 21): A sequence was not expected
```
